# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Louis Kiesewetter
description: >- # this means to ignore newlines until "baseurl:"
  This is my website
#baseurl: "/louispk.github.io" # the subpath of the site
url: "https://louispk.github.io" # the base hostname & protocol for the site
og_image: /assets/img/me_1_small_2.png
#google_analytics: "UA-121636368-3"

header:
  site-title: Louis Kiesewetter
  pages:
    - name: Home
      slug: /
    - name: About Me
      slug: /about
    - name: Work
    - name: Bicycles

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: louispk@proton.me
      link: mailto:louispk@proton.me
  follow:

    - name: LinkedIn
      link: https://www.linkedin.com/in/louis-kiesewetter-13b618210/
    - name: GitHub
      link: http://github.com/louispk
    - name: Instagram
      link: http://instagram.com/louisphk
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
